## configuration.yaml
homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 65
  unit_system: metric
  time_zone: Australia/Sydney
  customize: !include includes/customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - !secret subnet1
        - !secret subnet2
      allow_bypass_login: true

  whitelist_external_dirs:
    - '/config/www/sounds'

frontend:
  themes: !include_dir_merge_named ../themes

recorder:
  purge_keep_days: 14

logbook:
  exclude:
    domains:
      - sensor
      - media_player
      - binary_sensor
      - zwave
http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies: !secret proxy

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key

vera:
  vera_controller_url: !secret vera_url
  lights: [18, 19, 26, 28, 29, 33, 38, 86]
  exclude: []

# solaredge:
#   api_key: !secret solaredge_api_key
#   site_id: !secret solaredge_site_id
#   name: SolarEdge

# bmw_connected_drive:
#   bmw_x5:
#     username: !secret USERNAME_BMW_CONNECTED_DRIVE
#     password: !secret PASSWORD_BMW_CONNECTED_DRIVE
#     region: rest_of_world

# speedtestdotnet:
#   server_id: 2629
#   monitored_conditions:
#     - ping
#     - download
#     - upload
#   scan_interval:
#     hours: 6

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

# apcupsd:
#   host: !secret apc_ups_host
#   port: !secret apc_ups_port

## this now configured from the inergration GUI
# remote_homeassistant:
#   instances:
#   - host: !secret ha_lounge_ip
#     port: !secret ha_lounge_port
#     secure: false
#     access_token: !secret ha_lounge_access_token
#     entity_prefix: "ha_lounge_"
#     include:
#       domains:
#       - script
#       - input_boolean
#    subscribe_events:
#    - deconz_event

tts:
  - platform: google_translate
    base_url: !secret tts_base_url

# webostv:
#   host: !secret play_room_tv_host
#   name: Play Room TV
#   turn_on_action:
#     service: wake_on_lan.send_magic_packet
#     data:
#       mac: !secret play_room_tv_mac
#   customize:
#     sources:
#       - livetv
#       - youtube
#       - iview
#       - netflix
#       - Plex
#       - stan
config:
mobile_app:
person:
history:
discovery:
map:
sun:
wake_on_lan:
stream:
zeroconf:
system_health:
updater:

## Includes
light: !include includes/lights.yaml
lovelace: !include includes/lovelace.yaml
weather: !include includes/weather.yaml
input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
sensor: !include includes/sensors.yaml
switch: !include includes/switch.yaml
binary_sensor: !include includes/binary_sensor.yaml
timer: !include includes/timer.yaml
device_tracker: !include includes/device_tracker.yaml
scene: !include includes/scenes.yaml
group: !include includes/groups.yaml
zone: !include includes/zones.yaml
notify: !include includes/notify.yaml
media_player: !include includes/media_player.yaml
camera: !include includes/camera.yaml
webostv: !include includes/webostv.yaml
#samsungtv: !include includes/samsungtv.yaml

##DEPRICATED
##doorbird: !include includes/doorbird.yaml


## Dir Includes
automation: !include_dir_merge_list automation
script: !include_dir_merge_named scripts
#packages:  !include_dir_named packages
#above packages is a dir, each yaml in packages is named as a rom/purpose, and headings are base as in configuration.yaml
