# ui-camera-girls.yaml
title: Cameras
views:
-   panel: true
    cards:
      - type: picture-entity
        entity: camera.frontcam
        camera_view: live
        tap_action:
          action: navigate
          navigation_path: /ui-ipad/0
