# ui-camera-front-gate.yaml
title: Cameras
views:
-   panel: true
    cards:
      - type: picture-entity
        entity: camera.front_gate_live
        camera_view: live
        tap_action:
          action: navigate
          navigation_path: /ui-ipad/0
