# ui-lovelace.yaml
title: iPhone

views:
  - icon: mdi:home
    badges:
      # - entity: device_tracker.darren_reynolds
      # - entity: device_tracker.blythe
      - entity: sensor.outside_temp
      - entity: sensor.dark_sky_summary_template
      - entity: sensor.template_bondi_max_temp
      - entity: sensor.template_bondi_min_temp
      # - entity: sensor.template_sensor_emoncms_net_grid_power
      # - entity: sensor.template_sensor_emoncms_house_consumption
      # - entity: sensor.template_sensor_emoncms_solar_production
      - entity: sensor.template_calendar_bin_nights
    cards:
      - type: vertical-stack
        show_header_toggle: true
        cards:
          - type: horizontal-stack
            show_header_toggle: true
            cards:
              - type: custom:button-card
                entity: input_boolean.morning_lights
                styles:
                  card:
                    - height: 80px
                  name:
                    - font-size: 15px
                    - white-space: initial
                    - text-overflow: initial
                    - overflow: initial
              - type: custom:button-card
                entity: input_boolean.lollie_lights
                styles:
                  card:
                    - height: 80px
                  name:
                    - font-size: 15px
                    - white-space: initial
                    - text-overflow: initial
                    - overflow: initial
              - type: custom:button-card
                entity: input_boolean.bed_time
                styles:
                  card:
                    - height: 80px
                  name:
                    - font-size: 15px
                    - white-space: initial
                    - text-overflow: initial
                    - overflow: initial
              - type: custom:button-card
                entity: input_boolean.open_front_gate
                styles:
                  card:
                    - height: 80px
                  name:
                    - font-size: 15px
                    - white-space: initial
                    - text-overflow: initial
                    - overflow: initial
          - entities:
            - input_select.house_mode
            - sensor.template_calendar_family
            show_header_toggle: false
            type: entities
          - type: horizontal-stack
            cards:
              - type: light
                entity:  light.kitchen_high_level_6
              - type: light
                entity: light.kitchen_low_level_4
              - type: light
                entity: light.bedside_lamp_darren
                name: Darren
          - type: horizontal-stack
            show_header_toggle: true
            cards:
              - type: custom:button-card
                entity: light.lounge_level_6
                styles:
                  card:
                    - height: 80px
                  name:
                    - font-size: 15px
                    - white-space: initial
                    - text-overflow: initial
                    - overflow: initial
              - type: custom:button-card
                entity: light.tv_level_8
                styles:
                  card:
                    - height: 80px
                  name:
                    - font-size: 15px
                    - white-space: initial
                    - text-overflow: initial
                    - overflow: initial
              - type: custom:button-card
                entity: light.master_bedroom_level
                styles:
                  card:
                    - height: 80px
                  name:
                    - font-size: 15px
                    - white-space: initial
                    - text-overflow: initial
                    - overflow: initial
              - type: custom:button-card
                entity: light.front_porch_light_86_2
                styles:
                  card:
                    - height: 80px
                  name:
                    - font-size: 15px
                    - white-space: initial
                    - text-overflow: initial
                    - overflow: initial
  - icon: mdi:stove
    cards:
      - type: vertical-stack
        title: Kitchen
        show_header_toggle: true
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity:  light.kitchen_high_level_6
              - type: light
                entity: light.kitchen_low_level_4
      - type: entities
        entities:
          - light.kitchen_bench_19_2
#          - entity: media_player.kitchen
#            icon: mdi:speaker-wireless
###        type: entities
      - type: custom:mini-media-player
        entity: media_player.kitchen
        name: Kitchen Sonos
        hide:
          power: true
          icon: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.lounge
              name: Lounge Sonos
      - type: vertical-stack
        title: Lounge
        show_header_toggle: true
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.lounge_level_6
              - type: light
                entity: light.tv_level_8
          - type: custom:mini-media-player
            entity: media_player.lounge
            name: Lounge Sonos
            hide:
              power: true
              icon: true
  #    - type: media-control
  #      entity: media_player.lounge
  - icon: mdi:bed-empty
    cards:
      - type: vertical-stack
        title: Lights
        show_header_toggle: true
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.master_bedroom_level
              - type: light
                entity: light.bedside_lamp_darren
          - type: custom:mini-media-player
            entity: media_player.master_bedroom_tv
            name: Master Bedroom TV
            hide:
              icon: true
          - type: custom:mini-media-player
            entity: media_player.master_bedroom
            name: Master Bedroom Sonos
            hide:
              icon: true
          # - type: entities
          #   entities:
          #   - entity: media_player.master_bedroom
          #     icon: mdi:speaker-wireless
          #     type: entities
      - type: entities
        entities:
            # Displays the light entity. It's optional
            - entity: light.bedside_lamp_darren

            # Card configuration starts here
            - type: 'custom:rgb-light-card'
              entity: light.bedside_lamp_darren
              justify: between
              colors:
                  # Any option of the light.turn_on service can be used in each color
                  - rgb_color:
                        - 255
                        - 64
                        - 0
                    brightness: 120
                    transition: 1
                  - rgb_color:
                        - 255
                        - 181
                        - 108
                    brightness: 100
                    transition: 1
                  # - rgb_color:
                  #       - 255
                  #       - 0
                  #       - 0
                  #   brightness: 100
                  #   transition: 1

                  # - hs_color:
                  #       - 60
                  #       - 30
                  #   icon_color: '#fff8b0' # Override icon color

  - icon: mdi:stairs
    cards:
      - entities:
        - light.stairs_33_2
        - entity: input_number.stairs_light_timer
          icon: mdi:timer
        show_header_toggle: false
        type: entities
        title: Stairs/Hall/Bathroom
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.hall_level_10
          - type: light
            entity: light.laundry_hall_37_2
      - entities:
        - entity: media_player.bathroom
          icon: mdi:speaker-wireless
        type: entities
  - icon: mdi:gate
    cards:
      - type: iframe
        url: !secret frontgate_stream
        aspect_ratio: 100%
  - icon: mdi:weather-partly-cloudy
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
        name: Sydney Weather
      - entity: camera.bom_radar_loop_sydney
        type: picture-entity
        title: BOM Radar
      - type: sensor
        entity: sensor.outside_temp
        name: Outside Temperature
        graph: line
        icon: mdi:thermometer
        hours_to_show: 24
        detail: 2
  - icon: mdi:cctv
    cards:
      - entity: camera.frontcam
        type: picture-entity
      - entity: camera.nurserycam
        type: picture-entity
      - entity: camera.front_gate_live
        type: picture-entity
      - entity: camera.front_gate_last_ring
        type: picture-entity
  - icon: mdi:solar-power
    cards:
      - entities:
        - sensor.solaredge_current_power_template
        - sensor.solaredge_energy_today_template
        - sensor.solaredge_energy_this_month_template
        - sensor.solaredge_energy_this_year_template
        - sensor.solaredge_lifetime_energy_template
        type: entities
        show_header_toggle: false
        title: SolarEdge
      - entities:
        - sensor.template_sensor_emoncms_net_grid_power
        - sensor.template_sensor_emoncms_house_consumption
        - sensor.template_sensor_emoncms_solar_production
        type: entities
        show_header_toggle: false
        title: EmonCMS
      - type: sensor
        entity: sensor.solaredge_current_power_template
        name: Solar Power
        graph: line
        icon: mdi:solar-power
        hours_to_show: 24
        detail: 2
  - icon: mdi:tree
    cards:
      - entities:
        - light.back_floodlights_26_2
        - light.back_garden_29
        - light.side_28_2
        - entity: switch.back_deck_watering_25_2
          name: Back Deck watering
          icon: mdi:water
        - entity: input_number.backdeck_watering_timer
          name: Timer
          icon: mdi:timer
        type: entities
        title: Backyard
      - entities:
        - light.front_porch_light_86_2
        - switch.frontyard
        - switch.front_gate_ir
        - entity: media_player.front_garden
          icon: mdi:speaker-wireless
        show_header_toggle: false
        type: entities
        title: Frontyard
      - entity: camera.front_gate_live
        type: picture-entity
      - entity: camera.front_gate_last_ring
        type: picture-entity
  - icon: mdi:car-side
    cards:
      - entities:
          - lock.x5_xdrive30d_lock
        title: Lock
        type: entities
      - entities:
        - device_tracker.x5_xdrive30d
        - sensor.template_x5_xdrive30d_mileage
        - sensor.template_x5_xdrive30d_remaining_fuel
        - sensor.template_x5_xdrive30d_remaining_range_fuel
        - binary_sensor.x5_xdrive30d_lights_parking
        - binary_sensor.x5_xdrive30d_door_lock_state
        - sensor.template_binary_sensor_x5_xdrive30d_windows_front
        - sensor.template_binary_sensor_x5_xdrive30d_windows_rear
        - sensor.template_binary_sensor_x5_xdrive30d_front_doors
        - sensor.template_binary_sensor_x5_xdrive30d_rear_doors
        - sensor.template_binary_sensor_x5_xdrive30d_bonnet_rear
        - sensor.template_binary_sensor_x5_xdrive30d_sunroof
        title: Car
        type: entities
        show_header_toggle: false
      - entity: camera.bmw_x5_location
        type: picture-entity
      - entities:
        - sensor.333_to_beach_template
        - sensor.380_to_beach_template
        - sensor.bus_from_beach_template
        - sensor.333_to_bondi_junction
        - sensor.380_to_bondi_junction
        - sensor.381_to_bondi_junction
        title: Buses
        type: entities
        show_header_toggle: false
  - icon: mdi:help
    cards:
      - entity: media_player.master_bedroom_tv
        type: media-control
      - entity: media_player.front_garden
        type: media-control
      - entity: media_player.loungeroom_chromecast
        type: media-control
      - entity: media_player.lounge
        type: media-control
      - entity: media_player.bed_room_ua60h7000
        type: media-control
      - entity: media_player.study
        type: media-control
      - entity: camera.front_gate_last_motion
        type: picture-entity
      - entity: media_player.lounge_ua65js8000
        type: media-control
      - entity: media_player.ensuite
        type: media-control
      - entity: media_player.girl_s_room
        type: media-control
      - entities:
          - switch.kitchen_sensor_20
          - switch.uv_sensor_81
          - switch.front_door_30_2
          - switch.girls_room_66
          - switch.aeon_labs_dsc12104_micro_smart_energy_switch_switch
        title: Switch
        type: entities
      - entities:
          - zwave.aeon_labs_zw090_z_stick_gen5_au
          - zwave.aeon_labs_dsc19103_micro_smart_dimmer_2nd_edition
          - zwave.aeon_labs_dsc19103_micro_smart_dimmer_2nd_edition_2
          - zwave.aeon_labs_dsc12104_micro_smart_energy_switch
          - zwave.unknown_node_4
        title: Z-Wave
        type: entities
#      - type: glance
#        title: Glance card sample
#        entities:
#          - device_tracker.darren_reynolds
#          - device_tracker.blythe
#          - entity: sensor.outside_temp
#            icon: mdi:thermometer
#          - sensor.dark_sky_summary_template
#          - sensor.template_bondi_max_temp
#          - sensor.template_calendar_bin_nights

# example horizontal stack of buttons for house mode
#      - type: vertical-stack
#        cards:
#          - type: "custom:button-card"
#            color_type: label-card
#            color: rgb(44, 109, 214)
#            name: House Mode
#          - type: horizontal-stack
#            cards:
#              - type: "custom:button-card"
#                entity: house_mode_day
#                color_type: card
#                color: rgb(66, 134, 244)
#                icon: mdi:numeric-1-box-outline
#              - type: "custom:button-card"
#                entity: house_mode_evening
#                color_type: card
#                color: rgb(66, 134, 244)
#                icon: mdi:numeric-2-box-outline
#              - type: "custom:button-card"
#                entity: house_mode_bedtime
#                color_type: card
#                color: rgb(66, 134, 244)
#                icon: mdi:numeric-3-box-outline
#              - type: "custom:button-card"
#                entity: house_mode_night
#                color_type: card
#                color: rgb(66, 134, 244)
#                icon: mdi:numeric-4-box-outline
#              - type: "custom:button-card"
#                entity: house_mode_holiday
#                color_type: card
#                color: rgb(66, 134, 244)
#                icon: mdi:eye-off-outline
