# ui-test.yaml
title: Test

views:
  - icon: mdi:test-tube
#    panel: true
    # badges:
    #   - entity: sensor.template_calendar_bin_nights
    #   - entity: binary_sensor.kitchen_sensor_116
    #   - entity: sensor.temperature_sensor_117
    cards:
      - entities:
        - sensor.template_house_mode
        - light.decksteps_master
        - light.decksteps_segment_1
        - light.decksteps_segment_2
        - light.decksteps_segment_3
        - binary_sensor.dark
        - sensor.sun_azimuth_template
        - sensor.sun_elevation_template
        - script.vergola_open_all
        - script.vergola_close_all
        - switch.vergola_select
        - switch.vergola_auto
        - switch.vergola_close
        - switch.vergola_open
        - switch.subwoofer
        - sensor.bathroom_humidity
        - sensor.bathroom_temperature
        - binary_sensor.bathroom_motion
        - binary_sensor.kitchen_motion
        - binary_sensor.laundry_motion
        - light.bathroom_level
        - light.girl_s_lamp
        - light.bargeboard_master
        - light.bargeboard
        - light.bargeboard_segment_1
        - light.bargeboard_segment_2
        - input_boolean.announce_test
        - light.bedside_lamp_darren
        - sensor.turntable_watts
        - sensor.washerpanel_watts
        - sensor.dryerpanel_watts
        - sensor.dishwasher_watts
        - sensor.xmas_lights_watts
        show_header_toggle: false
        type: entities
      - type: custom:mini-media-player
        entity: media_player.yamaha_receiver
        name: Yamaha Receiver
        volume_stateless: true
        hide:
          power: true
          icon: true
        # shortcuts:
        #   columns: 3 # Max buttons per row
        #   buttons:
        #     # Start predefined playlist
        #     - icon: mdi:emoticon-cool-outline
        #       type: playlist
        #       id: spotify:user:spotify:playlist:37i9dQZF1DZ06evO2O09Hg
        #     # Change the source to bathroom
        #     - icon: mdi:dog
        #       type: source
        #       id: Bathroom
        #     # Trigger script
        #     - icon: mdi:dog
        #       type: script
        #       id: script.script_name
      - type: custom:button-card
        entity: input_boolean.ha_lounge_hdmi_power
        styles:
          card:
            - height: 80px
          name:
            - font-size: 15px
            - white-space: initial
            - text-overflow: initial
            - overflow: initial
      - type: custom:mini-media-player
        entity: media_player.plex_plex_for_samsung_tv_ua65js8000
        name: Plex Lounge
        artwork: cover
        hide:
          icon: true
          power: true
          volume: true
          runtime: false
          play_stop: false
      - type: custom:mini-media-player
        entity: media_player.plex_plex_for_samsung_tv_ua60h7000
        name: Plex Master Bedroom
        artwork: cover
        hide:
          icon: true
          power: true
          volume: true
          runtime: false
          play_stop: false
      - type: sensor
        entity: sensor.dryer_watts
        name: Dryer Power
        graph: line
      - type: sensor
        entity: sensor.dishwasher_watts
        name: Dishwasher Power
        graph: line
      - type: sensor
        entity: sensor.washer_watts
        name: Washing Machine Power
        graph: line
      - type: sensor
        entity: sensor.temperature_sensor_129
        name: Kitchen Temp
        graph: line
      - type: sensor
        entity: sensor.light_sensor_130
        name: Kitchen Lux
        graph: line
      - type: sensor
        entity: sensor.laundry_temperature
        name: Laundry Temp
        graph: line
      - type: sensor
        entity: sensor.laundry_humidity
        name: Laundry Humidity
        graph: line
      - type: custom:bom-weather-card
        title: BOM Weather
        entity_current_conditions: sensor.bom_sydney_icon_0
        entity_temperature: sensor.bom_sydney_air_temp_c
        entity_forecast_high_temp_1: sensor.bom_sydney_max_temp_c_1
        entity_forecast_high_temp_2: sensor.bom_sydney_max_temp_c_2
        entity_forecast_high_temp_3: sensor.bom_sydney_max_temp_c_3
        entity_forecast_high_temp_4: sensor.bom_sydney_max_temp_c_4
        entity_forecast_high_temp_5: sensor.bom_sydney_max_temp_c_5
        entity_forecast_icon_1: sensor.bom_sydney_icon_1
        entity_forecast_icon_2: sensor.bom_sydney_icon_2
        entity_forecast_icon_3: sensor.bom_sydney_icon_3
        entity_forecast_icon_4: sensor.bom_sydney_icon_4
        entity_forecast_icon_5: sensor.bom_sydney_icon_5
        entity_forecast_low_temp_1: sensor.bom_sydney_min_temp_c_1
        entity_forecast_low_temp_2: sensor.bom_sydney_min_temp_c_2
        entity_forecast_low_temp_3: sensor.bom_sydney_min_temp_c_3
        entity_forecast_low_temp_4: sensor.bom_sydney_min_temp_c_4
        entity_forecast_low_temp_5: sensor.bom_sydney_min_temp_c_5
        entity_summary_1: sensor.bom_sydney_summary_1
        entity_summary_2: sensor.bom_sydney_summary_2
        entity_summary_3: sensor.bom_sydney_summary_3
        entity_summary_4: sensor.bom_sydney_summary_4
        entity_summary_5: sensor.bom_sydney_summary_5
        entity_sun: sun.sun
        # entity_visibility: sensor.dark_sky_visibility
        entity_daytime_high: sensor.bom_today_max
        entity_daytime_low: sensor.bom_today_min
        entity_wind_bearing: sensor.bom_sydney_wind_direction
        entity_wind_speed: sensor.bom_sydney_wind_speed_kmh
        entity_humidity: sensor.bom_sydney_relative_humidity
        # entity_pressure: sensor.dark_sky_pressure
        entity_apparent_temp: sensor.bom_sydney_feels_like_c
        entity_daily_summary: sensor.bom_sydney_detailed_summary_0
        entity_pop: sensor.bom_sydney_chance_of_rain_0
        entity_pop_intensity: sensor.bom_sydney_rain_today
        entity_possible_today: sensor.bom_sydney_possible_rainfall_0
        entity_pos_1: sensor.bom_sydney_possible_rainfall_1
        entity_pos_2: sensor.bom_sydney_possible_rainfall_2
        entity_pos_3: sensor.bom_sydney_possible_rainfall_3
        entity_pos_4: sensor.bom_sydney_possible_rainfall_4
        entity_pos_5: sensor.bom_sydney_possible_rainfall_5
        entity_pop_1: sensor.bom_sydney_chance_of_rain_1
        entity_pop_2: sensor.bom_sydney_chance_of_rain_2
        entity_pop_3: sensor.bom_sydney_chance_of_rain_3
        entity_pop_4: sensor.bom_sydney_chance_of_rain_4
        entity_pop_5: sensor.bom_sydney_chance_of_rain_5
        entity_current_text: sensor.bom_current_text
        entity_uv_alert: sensor.bom_uv_alert
        entity_fire_danger: sensor.bom_fire_danger
        entity_uv_alert_summary: sensor.bom_uv_alert_summary
        entity_fire_danger_summary: sensor.bom_fire_danger_summary
        locale: en
        sunset: true
        static_icons: false
        #           old_icon: "true"
        tooltip_bg_color: 'rgb( 75,155,239)'
        tooltip_border_color: 'rgb(255,161,0)'
        tooltip_border_width: 1
        tooltip_caret_size: 5
        tooltip_fg_color: '#fff'
        tooltip_left_offset: -12
        tooltip_width: 110
        tooltips: true
        old_daily_format: false
        time_format: 12
        show_beaufort: false
        refresh_interval: 60
        show_separator: false
        temp_top_margin: -0.3em         #default -0.3em px or em
        temp_font_weight: 300           #default 300 numeric
        temp_font_size: 4em             #default 4em em
        temp_right_pos: 0.85em          #default .85em px or em
        temp_uom_top_margin: -9px       #default -9px px or em
        temp_uom_right_margin: 7px      #default 7px px or em
        apparent_top_margin: 45px       #default 45px px or em
        apparent_right_pos: 1em         #default 1em px or em
        apparent_right_margin: 1em      #default 1em px or em
        current_text_top_margin: 4.5em  #default 39px px or em
        current_text_left_pos: 0em      #default 5em px or em
        current_text_font_size: 1.5em   #default 1.5em em
        current_text_alignment: center  #default center
        current_text_width: 100%        #default 100%
        current_data_top_margin: 10em   #default 7em px or em
        large_icon_top_margin: -3.5em   #default -3.5em px or em
        large_icon_left_position: 0em   #default 0em px or em
        separator_top_margin: 6em       #default 6em px or em
        summary_top_padding: 2em        #default 1em px or em
        summary_font_size: 0.8em        #default 0.8em px or em
        slot_l1: daytime_high           #daytime_high
        slot_l2: daytime_low            #daytime_low
        slot_l3: wind                   #wind
        slot_l4: pressure               #pressure
        slot_l5: sun_next               #sun_next
        slot_r1: pop                    #pop
        slot_r2: humidity               #humidity
        slot_r3: uv_alert               #uv_alert
        slot_r4: fire_danger            #fire_danger
        slot_r5: sun_following          #sun_following
