## general.yaml automations

- alias: "Weekely Devices Low Battery Warning"
  mode: single
  variables:
    day: 1
    threshold: 20
    sensors: >-
      {% set result = namespace(sensors=[]) %}
      {% for state in states.sensor | selectattr('attributes.device_class', '==', 'battery') %}
        {% if 0 <= state.state | int(-1) < threshold | int %}
          {% set result.sensors = result.sensors + [state.name ~ ' (' ~ state.state ~ ' %)'] %}
        {% endif %}
      {% endfor %}
      {% for state in states.binary_sensor | selectattr('attributes.device_class', '==', 'battery') | selectattr('state', '==', 'on') %}
        {% set result.sensors = result.sensors + [state.name] %}
      {% endfor %}
      {{result.sensors|join(', ')}}
  # run only on Thurs (day 4) at 9;30 am
  trigger:
  - platform: time
    at: "09:30:00"
  condition:
  - condition: template
    value_template: '{{ sensors != '''' and (4 == now().isoweekday()) }}'
  action:
    - service: notify.mobile_app_darren_reynolds
      data:
        message: "Weekly Low battery warning: {{sensors}}"

- alias: Kitchen Vol down stop
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_sonos
        event: 3003
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.kitchen_down_stop

- alias: "Front Door switch - Playroom off"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: front_door_switch
        event: 1002
  action:
    - service: script.turn_on
      target:
        entity_id: script.playroom_off

- alias: Kitchen Vol up stop
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_sonos
        event: 2003
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.kitchen_up_stop

- alias: Front Door Open
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Bedtime'
    - platform: state
      entity_id: input_select.house_mode
      to: 'Night'
  condition:
    condition: state
    entity_id: binary_sensor.front_door_30
    state: 'on'
  action:
    - service: script.announce
      data:
        sonos_entity: media_player.kitchen
        volume: 0.3
        message: 'The front door is still open'
        delay: '00:00:05'
    - service: notify.mobile_app_darren_reynolds
      data:
        message: "Front Door Still OPEN!"

- alias: Car Unlocked Late
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Bedtime'
    - platform: state
      entity_id: input_select.house_mode
      to: 'Night'
  condition:
    condition: state
    entity_id: binary_sensor.x5_xdrive30d_door_lock_state
    state: 'on'
  action:
    - service: script.announce
      data:
        sonos_entity: media_player.kitchen
        volume: 0.3
        message: 'The car is unlocked'
        delay: '00:00:04'
    - service: notify.mobile_app_darren_reynolds
      data:
        message: "Car UNLOCKED!"
- alias: Car Windows Late
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Bedtime'
    - platform: state
      entity_id: input_select.house_mode
      to: 'Night'
  condition:
    condition: state
    entity_id: binary_sensor.x5_xdrive30d_windows
    state: 'on'
  action:
    - service: script.announce
      data:
        sonos_entity: media_player.kitchen
        volume: 0.3
        message: 'The car windows or sunroof is still open'
        delay: '00:00:06'
    - service: notify.mobile_app_darren_reynolds
      data:
        message: "Car windows or sunroof OPEN!"
- alias: Car Unlocked
  trigger:
    - platform: state
      entity_id: device_tracker.x5_xdrive30d
      to: 'home'
      for:
        minutes: 15
  condition:
    condition: state
    entity_id: binary_sensor.x5_xdrive30d_door_lock_state
    state: 'on'
  action:
    - service: script.announce
      data:
        sonos_entity: media_player.kitchen
        volume: 0.3
        message: 'The car is unlocked'
        delay: '00:00:04'
    - service: notify.mobile_app_darren_reynolds
      data:
        message: "Car still UNLOCKED!"

- alias: Car Windows
  trigger:
    - platform: state
      entity_id: device_tracker.x5_xdrive30d
      to: 'home'
      for:
        minutes: 15
  condition:
    condition: state
    entity_id: binary_sensor.x5_xdrive30d_windows
    state: 'on'
  action:
    - service: script.announce
      data:
        sonos_entity: media_player.kitchen
        volume: 0.3
        message: 'The car windows or sunroof is open'
        delay: '00:00:06'
    - service: notify.mobile_app_darren_reynolds
      data:
        message: "Car windows or sunroof OPEN!"

- alias: "Tasmota State on HA Restart"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/tasmotas/backlog"
        payload: "power1 ;power2 ;power3 ;power4 ;power5; dimmer; state "

# - alias: 'Update BOM Icons'
#   trigger:
#     - event: start
#       platform: homeassistant
#     - entity_id: sun.sun
#       platform: state
#       to: 'above_horizon'
#     - entity_id: sun.sun
#       platform: state
#       to: 'below_horizon'
#   action:
#     - service: homeassistant.update_entity
#       entity_id: sensor.bom_forecast_0, sensor.bom_forecast_1, sensor.bom_forecast_2, sensor.bom_forecast_3, sensor.bom_forecast_4, sensor.bom_forecast_5, sensor.bom_forecast_6


# ## Auto change themes
# - alias: hass_theme
#   trigger:
#     - platform: state
#       entity_id: input_select.hass_theme
#   action:
#     - service: frontend.set_theme
#       data_template:
#         name: "{{ states.input_select.hass_theme.state }}"
