### house_mode.yaml automation

## Automated Select Scenes - House modes Evening, Night and Day (Bedtime and Holiday only called manually)

- alias: Set Evening mode at Sunset
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      # after sunset
      below: 1.0
    - platform: numeric_state
      entity_id: sensor.light_sensor_130 # this updates fom the Z-wave sensor every 1 min
      below: 25
  condition:
    - condition: state
      entity_id: binary_sensor.before_sunset
      state: 'on'
    - condition: state
      entity_id: input_boolean.evening_lights_on_flag
      state: 'off'
  action:
    - service: logbook.log
      data_template:
        name: 'Sunset:'
        message: 'Evening lights turned ON by {{trigger.entity_id}}'
    - service: notify.mobile_app_darren_reynolds
      data:
        message: 'Evening lights on by {{ trigger.entity_id.friendly_name }}'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.evening_lights_on_flag
    #Everyday except WED (non-bin nights)
    #turn on Bargeboard light based on input_select.bb_colour
    - choose:
      #IF Holiday house mode - turn on only select lights
        - conditions:
            - condition: state
              entity_id: input_select.house_mode
              state: 'Holiday'
          sequence:
            - service: logbook.log
              data_template:
                name: "Evening Lights"
                message: for HOLIDAY house mode ON
            - service: input_boolean.turn_on
              entity_id: input_boolean.evening_holiday
            - service: light.turn_on
              entity_id: light.kitchen_bench_19_2
            - service: switch.turn_on
              entity_id: switch.frontyard
            - service: scene.turn_on
              data_template:
                entity_id: >
                 {% if now().isoweekday() != 3 %}
                   scene.bb_{{states.input_select.bb_colour.state}}
                 {% else %}
                   scene.nothing
                 {% endif %}
      # ELSE - any other house mode - input select Evening - which will call the evening script
      default:
        - service: input_select.select_option
          data:
            entity_id: input_select.house_mode
            option: Evening

- alias: "House Mode Evening"
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: 'Evening'
  action:
    - service: script.turn_on
      entity_id: script.evening

- alias: Auto Set Night mode
  trigger:
    platform: time
    at: '22:30:00'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.house_mode", "Holiday") %}
            script.night_holiday
          {% else %}
            script.night
          {% endif %}
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.evening_lights_on_flag

- alias: Set Day mode
  trigger:
    platform: time
    at: '05:30:00'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("input_select.house_mode", "Holiday") %}
            script.day_holiday
          {% else %}
            script.day
          {% endif %}

- alias: House mode Bedtime - lights off
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: 'Bedtime'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights_not_beds
    # - service: light.turn_off
    #   entity_id:
    #     - light.kitchen_high_level_6
    #     - light.kitchen_low_level_4
    #     - light.kitchen_bench_19_2
    #     - light.lounge_level_6
    #     - light.tv_level_8
    #     - light.ha_lounge_lounge_lamp
    #     - light.stairs_33_2
    #     - light.laundry_hall_37_2
    #     - light.hall_level_10
    #     - light.front_porch_light_86_2
    #     - light.back_garden_29
    #     - light.trampoline
    #     - light.decksteps_master
    #     # - group.all_lights_not_beds
    # - service: switch.turn_off
    #   entity_id:
    #     - switch.deck_heater
    #     - switch.backyard_floodlight
    #     - switch.back_deck
    #     - switch.water_lawn
    #     - switch.water_garden
    #     - switch.water_hedge

- alias: "Bargeboard Bin lights"
  trigger:
    platform: time
    at: '16:00:00'
  condition:
    - condition: time
      weekday:
        - wed
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
           {%if states.calendar.bin_nights.attributes.message == 'Red Yellow Bins' %}
              scene.bb_yellow_bins
           {% elif states.calendar.bin_nights.attributes.message == 'Red Blue Green Bins' %}
              scene.bb_blue_green_bins
           {% else %}
             scene.nothing
           {% endif %}
# mode mode evening backuo
# - alias: "House Mode Evening"
#   trigger:
#     platform: state
#     entity_id: input_select.house_mode
#     to: 'Evening'
#   action:
#     - service: scene.turn_on
#       data:
#         entity_id: scene.evening
# # vary scene if it's Wednesday (day 3)
#     - service: scene.turn_on
#       data_template:
#         entity_id: >
#          {% if now().isoweekday() == 3 %}
#            {%if states.calendar.bin_nights.attributes.message == 'Red Yellow Bins' %}
#               scene.bb_yellow_bins
#            {% elif states.calendar.bin_nights.attributes.message == 'Red Blue Green Bins' %}
#               scene.bb_blue_green_bins
#            {% endif %}
#          {% else %}
#            scene.bb_pink
#          {% endif %}

- alias: "House Mode Day"
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: 'Day'
  action:
    - service: script.turn_on
      entity_id: script.day

- alias: "House Mode Night"
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: 'Night'
  action:
    - service: script.turn_on
      entity_id: script.night

- alias: "House Mode Holiday"
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: 'Holiday'
  action:
    - service: notify.ios_darren
      data:
        message: "Holiday mode set"
        data:
          push:
            badge: 5
          subtitle: "Mode"

- alias: "House Mode Holiday Off"
  trigger:
    platform: state
    entity_id: input_select.house_mode
    from: 'Holiday'
  action:
    - service: notify.ios_darren
      data:
        message: "Holiday mode OFF"
        data:
          push:
            badge: 5
          subtitle: "Mode"
    - service: input_boolean.turn_off
      entity_id: input_boolean.evening_holiday

#these allow a button press to change the House Mode input select
#- alias: "House Mode  Select"
#  trigger:
#    platform: state
#    entity_id: input_boolean.house_mode_
#    from: 'on'
#  action:
#    - service: input_select.select_option
#      data:
#        entity_id: input_select.house_mode
#        option: ''
#    - service: input_boolean.turn_off
#      entity_id: input_boolean.house_mode_
