# open_front_gate.yaml automation
- alias: "Open Front Gate"
  trigger:
    - platform: state
      entity_id: input_boolean.open_front_gate
      to: 'on'
    - platform: event
      event_type: deconz_event
      event_data:
        id: front_door_switch
        event: 2002
    - platform: tag
      tag_id: 742cb4f2-540e-4678-96d4-e0f91bd2a357
  action:
    - service: switch.turn_on
      entity_id: switch.front_gate_relay_1
    - delay:
        seconds: 2
#    - service: switch.turn_off
#      entity_id: switch.front_gate_relay_1
    - service: input_boolean.turn_off
      entity_id: input_boolean.open_front_gate
