## tests.yaml automations

- alias: "'Toggle light test'"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 1002
  action:
    - service: light.toggle
      target:
        entity_id: light.tv_level_8

- alias: "'ON light test Lounge'"
  # initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_on_off_switch
        event: 1002
  action:
    - service: light.turn_on
      target:
        entity_id: light.blythe_s_lamp
- alias: "'OFF light test Lounge'"
  # initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_on_off_switch
        event: 2002
  action:
    - service: light.turn_off
      target:
        entity_id: light.blythe_s_lamp

- alias: "Increase brightness test"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 2002
  action:
    - service: light.turn_on
      target:
        entity_id: light.tv_level_8
      data:
        brightness: >
          {% set bri = state_attr('light.tv_level_8', 'brightness') | int %}
          {{ [bri+30, 249] | min }}
- alias: "Decrease brightness of lamp from dimmer"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 3002
  action:
    - service: light.turn_on
      target:
        entity_id: light.tv_level_8
      data:
        brightness: >
          {% set bri = state_attr('light.tv_level_8', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

- alias: test
  trigger:
    platform: state
    from: 'off'
    to: 'on'
    entity_id: input_boolean.tester
  action:
    - service: timer.start
      data_template:
        entity_id: timer.water_lawn
        duration: >
          00:{{ states.input_number.water_lawn_timer.state | int }}:00
    - service: notify.mobile_app_darren_reynolds
      data:
        message: 'Successful notify test'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.tester

- alias: test announce
  trigger:
    platform: state
    from: 'off'
    to: 'on'
    entity_id: input_boolean.announce_test
  action:
    - service: script.announce
      data:
        sonos_entity: media_player.study
        volume: 0.1
        message: 'a'
        delay: '00:00:01'
        at_night: 'no'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.announce_test

- alias: Doorbell test
  trigger:
    platform: state
    entity_id: input_boolean.doorbell_test
    to: 'on'
  action:
    - service: media_player.media_play_pause
      target:
        entity_id: media_player.kitchen

    # - service: logbook.log
    #   data:
    #     name: "Doorbell:"
    #     message: Test button pushed
    # - service: script.turn_on
    #   data:
    #     entity_id: script.doorbell
    # - service: input_boolean.turn_off
    #   data:
    #     entity_id: input_boolean.doorbell_test
