## tests.yaml automations

- alias: "tag test"
  trigger:
    - platform: state
      from: 'off'
      to: 'on'
      entity_id: input_boolean.lockdown
    # - platform: tag
    #   tag_id: 742cb4f2-540e-4678-96d4-e0f91bd2a357
  action:
    # - service: notify.mobile_app_darren_reynolds
    #   data:
    #     message: "Gate tag swiped!"
    - alias: "Ask for actions"
      service: notify.mobile_app_darren_reynolds
      data:
        message: "Test Action"
        data:
          actions:
            - action: "1"
              title: "One"
            - action: "2"
              title: "Two"
            - action: "3"
              title: "Three"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.lockdown

- alias: "Toggle light test"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 1002
  action:
    - service: light.toggle
      target:
        entity_id: light.tv_level_8


- alias: "Increase brightness test"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 2002
  action:
    - service: light.turn_on
      target:
        entity_id: light.tv_level_8
      data:
        brightness: >
          {% set bri = state_attr('light.tv_level_8', 'brightness') | int %}
          {{ [bri+30, 249] | min }}
- alias: "Decrease brightness of lamp from dimmer"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 3002
  action:
    - service: light.turn_on
      target:
        entity_id: light.tv_level_8
      data:
        brightness: >
          {% set bri = state_attr('light.tv_level_8', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

- alias: test
  trigger:
    - platform: state
      from: 'off'
      to: 'on'
      entity_id: input_boolean.tester
  # condition:
  #   condition: state
  #   entity_id:
  #     - binary_sensor.front_door_30
  #     - binary_sensor.ha_lounge_back_door
  #   state: 'on'
  action:
    - service: notify.mobile_app_darren_reynolds
      data:
        title: "Air Con"
        message: "Test toggled from {{trigger.from_state}} to {{trigger.to_state}}"
    # - service: script.announce
    #   data:
    #     sonos_entity: media_player.kitchen
    #     volume: 0.3
    #     message: "The {{ trigger.to_state.name }} is still open"
    #     delay: '00:00:04'
    # - service: notify.mobile_app_darren_reynolds
    #   data_template:
    #     message: "Trigger was: {{ state_attr(trigger.entity_id, 'friendly_name') }}"
    # - service: notify.mobile_app_darren_reynolds
    #   data_template:
    #     message: "{{ state_attr(trigger.entity_id, 'friendly_name') }} still OPEN!"
    - service: input_boolean.turn_off
      data_template:
        entity_id: input_boolean.tester
# {{ trigger.event.data.new_state.attributes.friendly_name | replace("Seventeentrack Package: ","") }}

    # - event: tileboard
    #   event_data:
    #     command: open_doorentry
    # - event: tileboard
    #   event_data:
    #     command: 'notify'
    #     id: '{{ context.id }}'
    #     lifetime: 5
    #     icon: 'mdi-information'
    #     type: 'info'
    #     title: 'Message'
    #     message: 'Test Message'
    # This below works!
    # - service: notify.mobile_app_darren_reynolds
    #   data:
    #     # message: "Trigger was: {{ trigger.event.data.friendly_name }}"
    #     message: "Trigger was: {{ state_attr(trigger.entity_id, 'friendly_name') }}"
    #     # message: 'Message: {{trigger.entity_id.attributes.friendly_name}}'

- alias: "Test Announce"
  trigger:
    platform: state
    entity_id: input_boolean.announce_test
    from: 'off'
    to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.notify_darren
      data:
        variables:
          message: 'Test announce'
    - service: script.announce
      data:
        sonos_entity: media_player.kitchen
        message: 'Announce test'
        delay: '00:00:03'
        not_at_night: yes
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.announce_test

- alias: "Doorbell test"
  trigger:
    platform: state
    entity_id: input_boolean.doorbell_test
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.fridge_tab_screen
    - event: tileboard
      event_data:
        command: 'doorbell'

    # - service: media_player.play_media
    #   data:
    #     entity_id: media_player.kitchen
    #     # media_content_id: http://10.0.26.20/sounds/doorbell.mp3
    #     media_content_id: "http://10.0.26.13:8123/local/sounds/doorbell.mp3"
    #     media_content_type: music

    # - service: logbook.log
    #   data:
    #     name: "Doorbell:"
    #     message: Test button pushed
    # - service: script.turn_on
    #   data:
    #     entity_id: script.doorbell
    # - service: input_boolean.turn_off
    #   data:
    #     entity_id: input_boolean.doorbell_test
