## tests.yaml automations

- alias: test notify
  trigger:
    platform: state
    from: 'off'
    to: 'on'
    entity_id: input_boolean.tester
  action:
    - service: notify.mobile_app_darren_reynolds
      data:
        message: 'Successful notify test'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.tester

- alias: test announce
  trigger:
    platform: state
    from: 'off'
    to: 'on'
    entity_id: input_boolean.announce_test
  action:
    - service: script.announce
      data:
        sonos_entity: media_player.study
        volume: 0.1
        message: 'a'
        delay: '00:00:01'
        at_night: 'no'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.announce_test

- alias: Doorbell test
  trigger:
    platform: state
    entity_id: input_boolean.doorbell_test
    to: 'on'
  action:
    - service: logbook.log
      data:
        name: "Doorbell:"
        message: Test button pushed
    - service: script.turn_on
      data:
        entity_id: script.doorbell
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.doorbell_test
