## tests.yaml automations

- alias: "tag test"
  trigger:
    - platform: state
      from: 'off'
      to: 'on'
      entity_id: input_boolean.lockdown
    # - platform: tag
    #   tag_id: 742cb4f2-540e-4678-96d4-e0f91bd2a357
  action:
    # - service: notify.mobile_app_darren_reynolds
    #   data:
    #     message: "Gate tag swiped!"
    - alias: "Ask for actions"
      service: notify.mobile_app_darren_reynolds
      data:
        message: "Test Action"
        data:
          actions:
            - action: "1"
              title: "One"
            - action: "2"
              title: "Two"
            - action: "3"
              title: "Three"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.lockdown

- alias: "Toggle light test"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 1002
  action:
    - service: light.toggle
      target:
        entity_id: light.tv_level_8


- alias: "Increase brightness test"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 2002
  action:
    - service: light.turn_on
      target:
        entity_id: light.tv_level_8
      data:
        brightness: >
          {% set bri = state_attr('light.tv_level_8', 'brightness') | int %}
          {{ [bri+30, 249] | min }}
- alias: "Decrease brightness of lamp from dimmer"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 3002
  action:
    - service: light.turn_on
      target:
        entity_id: light.tv_level_8
      data:
        brightness: >
          {% set bri = state_attr('light.tv_level_8', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

- alias: test
  trigger:
    - platform: state
      from: 'off'
      to: 'on'
      entity_id: input_boolean.tester
  action:
    - event: tileboard
      event_data:
        command: open_doorentry
    - service: notify.mobile_app_darren_reynolds
      data:
        # message: "Trigger was: {{ trigger.event.data.friendly_name }}"
        message: "Trigger was: {{ state_attr(trigger.entity_id, 'friendly_name') }}"
        # message: 'Message: {{trigger.entity_id.attributes.friendly_name}}'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.tester

- alias: "Test Announce"
  trigger:
    platform: state
    entity_id: input_boolean.announce_test
    from: 'off'
    to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.notify_darren
      data:
        variables:
          message: 'Test announce'
    - service: script.announce
      data:
        sonos_entity: media_player.kitchen
        message: 'Announce test'
        delay: '00:00:03'
        not_at_night: yes
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.announce_test

- alias: "Doorbell test"
  trigger:
    platform: state
    entity_id: input_boolean.doorbell_test
    to: 'on'
  action:
    - service: media_player.media_play_pause
      target:
        entity_id: media_player.kitchen

    # - service: logbook.log
    #   data:
    #     name: "Doorbell:"
    #     message: Test button pushed
    # - service: script.turn_on
    #   data:
    #     entity_id: script.doorbell
    # - service: input_boolean.turn_off
    #   data:
    #     entity_id: input_boolean.doorbell_test
