## camera.yaml
- platform: mjpeg
  name: nurserycam
  mjpeg_url: !secret nurserycam_url
  username: !secret nurserycam_uname
  password: !secret nurserycam_pass

- platform: mjpeg
  name: nurserycam_high
  mjpeg_url: !secret nurserycam_high_url
  username: !secret frontcam_uname
  password: !secret frontcam_pass

- platform: mjpeg
  name: frontcam
  mjpeg_url: !secret frontcam_url
  username: !secret frontcam_uname
  password: !secret frontcam_pass

- platform: mjpeg
  name: frontcam_high
  mjpeg_url: !secret frontcam_high_url
  username: !secret frontcam_uname
  password: !secret frontcam_pass

- platform: generic
  name: BMW X5 Location
  still_image_url: !secret x5_google_location
  limit_refetch_to_url_change: true
  scan_interval: 900

# - platform: doorbird
#   last_visitor: true

# - platform: bom
#   location: Sydney
