# lights.yaml

  # girls_bedroom_downlights:
  #   name: Girls Bedroom Downlights
  #   entities:
- platform: group
  name: Girls Bedroom Downlights
  entities:
    - light.ha_lounge_girls_room_1
    - light.ha_lounge_girls_room_2
    - light.ha_lounge_girls_room_3
    - light.ha_lounge_girls_room_4

- platform: mqtt
  name: "Blythe's Lamp"
  command_topic: "cmnd/blytheslamp/POWER"
  state_topic: "tele/blytheslamp/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/blytheslamp/LWT"
  brightness_command_topic: "cmnd/blytheslamp/Dimmer"
  brightness_state_topic: "tele/blytheslamp/STATE"
  brightness_scale: 100
  on_command_type: "last"
  brightness_value_template: "{{value_json.Dimmer}}"
  white_value_state_topic: "tele/blytheslamp/STATE"
  white_value_command_topic: "cmnd/blytheslamp/white"
  white_value_scale: 100
  white_value_template: "{{ value_json.Channel[3] }}"
  rgb_command_topic: "cmnd/blytheslamp/Color2"
  rgb_state_topic: "tele/blytheslamp/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/blytheslamp/Scheme"
  effect_state_topic: "tele/blytheslamp/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Girl's Lamp"
  command_topic: "cmnd/girlslamp/POWER"
  state_topic: "tele/girlslamp/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/girlslamp/LWT"
  brightness_command_topic: "cmnd/girlslamp/Dimmer"
  brightness_state_topic: "tele/girlslamp/STATE"
  brightness_scale: 100
  on_command_type: "last"
  brightness_value_template: "{{value_json.Dimmer}}"
  white_value_state_topic: "tele/girlslamp/STATE"
  white_value_command_topic: "cmnd/girlslamp/white"
  white_value_scale: 100
  white_value_template: "{{ value_json.Channel[3] }}"
  rgb_command_topic: "cmnd/girlslamp/Color2"
  rgb_state_topic: "tele/girlslamp/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/girlslamp/Scheme"
  effect_state_topic: "tele/girlslamp/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
