## media_player.yaml

- platform: yamaha_musiccast
  host: 10.0.26.29
  port: 5005

- platform: androidtv
  name: Lounge Google TV
  host: 10.0.26.23
  device_class: androidtv
  exclude_unnamed_apps: true
  apps:
    com.silicondust.view: "TV"
    com.netflix.ninja: "Netflix"
    au.net.abc.iview: "ABC iView"
    com.apple.atve.androidtv.appletv: "Apple TV"
    com.plexapp.android: "Plex"
    com.swm.live: "7+"
    au.com.ninenow.ctv: "9NOW"
    au.com.tenplay: "10 Play"
    com.tubitv: "tubi"
    com.google.android.youtube.tvkids: "YouTube Kids"
  state_detection_rules:
    'com.amazon.tv.launcher':
      - 'standby'
    'com.netflix.ninja':
      - 'media_session_state'
    'com.plexapp.android':
      - 'paused':
          'media_session_state': 3  # this indentation is important!
          'wake_lock_size': 1       # this indentation is important!
      - 'playing':
          'media_session_state': 3  # this indentation is important!
      - 'standby'
# - platform: yamaha
#   host: 10.0.26.29
#   zone_ignore:
#   - "Zone_2"
#   source_names:
#     HDMI1: "Foxtel"
#     HDMI2: "HA"
#     AUDIO1: "TV"
#     AUDIO4: "Turntable"

# - platform: universal
#   name: Lounge TV
#   children:
#     - media_player.lounge_main
#   commands:
#     turn_on:
#       service: script.turn_on
#       data: script.ha_lounge_tv_on
#     turn_off:
#       service: script.turn_off
#       data: script.ha_lounge_tv_on
#     volume_up:
#       service: SERVICE
#       data: SERVICE_DATA
#     volume_down:
#       service: SERVICE
#       data: SERVICE_DATA
#     volume_mute:
#       service: SERVICE
#       data: SERVICE_DATA
#   attributes:
#     is_volume_muted: ENTITY_ID|ATTRIBUTE
#     state: ENTITY_ID|ATTRIBUTE

#- platform: samsungtv_custom
#  host: 10.0.26.27
#  mac: 84:a4:66:07:dc:af
#  port: 8001
#  protocol: ws

#- platform: samsungtv_custom
#  host: 10.0.26.27
#  mac: 84:a4:66:07:dc:af
#  port: 8001
#  protocol: ws

#  protocol: ctl_qled
#  timeout: 5
#  name: LoungeTV
