### switch.yaml
switch:
- platform: switchbot
  mac: EA:96:2D:63:66:40

- platform: mqtt
  name: "Subwoofer"
  state_topic: "stat/subwoofer/POWER"
  command_topic: "cmnd/subwoofer/POWER"
  availability_topic: "tele/subwoofer/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Dryer"
  state_topic: "stat/dryer/POWER"
  command_topic: "cmnd/dryer/POWER"
  availability_topic: "tele/dryer/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Washer"
  state_topic: "stat/washer/POWER"
  command_topic: "cmnd/washer/POWER"
  availability_topic: "tele/washer/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Dishwasher"
  state_topic: "stat/dishwasher/POWER"
  command_topic: "cmnd/dishwasher/POWER"
  availability_topic: "tele/dishwasher/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Xmas Lights"
  state_topic: "stat/xmas/POWER"
  command_topic: "cmnd/xmas/POWER"
  availability_topic: "tele/xmas/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Turntable"
  state_topic: "stat/turntable/POWER"
  command_topic: "cmnd/turntable/POWER"
  availability_topic: "tele/turntable/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
