esphome:
  name: deckheater
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret esph-iot-SSID
  password: !secret esph-iot-pass
  power_save_mode: none
  fast_connect: on

logger:

api:
  password: !secret esph-api-pass

ota:
  password: !secret esph-ota-pass

# Device Specific Config
output:
  - platform: gpio
    pin: GPIO4
    id: relay

switch:
  - platform: output
    name: "Deck Heater"
    output: relay
    id: switchid

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      #mode: INPUT_PULLUP
      #inverted: True
    name: "Deck Heater Wall Switch"
    on_state:
      then:
        - switch.toggle: switchid
    internal: true
    id: wallswitchid
