esphome:
  name: vergola
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret esph-iot-SSID
  password: !secret esph-iot-pass
  power_save_mode: none
  fast_connect: on

logger:

api:
  password: !secret esph-api-pass

ota:
  password: !secret esph-ota-pass

switch:
  - platform: gpio
    name: "Vergola Select"
    pin: D2
  - platform: gpio
    name: "Vergola Auto"
    pin: D5
  - platform: gpio
    name: "Vergola Close"
    pin: D6
  - platform: gpio
    name: "Vergola Open"
    pin: D7
