esphome:
  name: wateringback
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret esph-iot-SSID
  password: !secret esph-iot-pass
  power_save_mode: none
  fast_connect: on

logger:

api:
  password: !secret esph-api-pass

ota:
  password: !secret esph-ota-pass

switch:
  - platform: gpio
    name: "water lawn"
    pin: D1
  - platform: gpio
    name: "water garden"
    pin: D5
  - platform: gpio
    name: "water hedge"
    pin: D6
